调试信息: false #debug mode
语言: zh_cn # 可选值：zh_cn/zh_tw/es_cu/lo_la/vi_vn/ko_kp
跨越时发送聊天栏消息: true #字面意思
boundary:
  世界1:
    x: 1000   # X轴最大边界（单位：方块）
    z: 1000   # Z轴最大边界
  世界2:
    x: 1000   # X轴最大边界（单位：方块）
    z: 1000   # Z轴最大边界
